version: "3.8"
networks:
  app-net:
    external: true
volumes:
  pgdata:

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: quickbite
      POSTGRES_USER: quickbite
      POSTGRES_PASSWORD: quickbite
    ports:
      - "5432:5432"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
       condition: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - app-net


  logic:
    image: dinhviet88/quickbite-logic:v1
    environment:
      #SPRING_DATASOURCE_URL: jdbc:h2:mem:quickbite
      #SPRING_DATASOURCE_USERNAME: sa
      #SPRING_DATASOURCE_PASSWORD: ''
      #SPRING_JPA_HIBERNATE_DDL_AUTO: update
      #SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quickbite
      SPRING_DATASOURCE_USERNAME: quickbite
      SPRING_DATASOURCE_PASSWORD: quickbite
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8081:8081"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - app-net

  gateway:
    image: dinhviet88/quickbite-gateway:v1
    environment:
      - LOGIC_URL=http://logic:8081
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - app-net

  frontend:
    image: dinhviet88/quickbite-frontend:v2
    environment:
      - API_GATEWAY_URL=/api
    ports:
      - "80:80"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - app-net